### ISSUE TITLE
Asset Updater: Endless ArgumentOutOfBoundsExceptions

### ISSUE THREAD

**Issue by michidk** [kode80/UnityTools#2] opened 2016-04-19 18:07 UTC
so the error appeared after is started unity, removed the old cloud system (by hand, because i modified some files), imported the new one via .unitypackage, opened the asset-updater and this happend:
![](https://pbs.twimg.com/media/Cga7tzvWwAAC4X7.jpg:large)
after reopening the window, the error didn't show again.

**Comment by kode80** [comment] 2016-04-19 18:44
What I suspect happened is there was a background download in progress. When you changed the files and opened the updater, it didn't cancel the existing background d/l, thus the Finished delegate was eventually called but now the internal list of local versions has changed so you got an out of bounds error.

Since the exception was thrown, the delegate never got a chance to be removed, so you got the never ending loop of callback->out of bounds exception->callback etc. As soon as you closed the window, the delegates were forcibly removed (killing the error) and then once you reopened the window, everything was fresh and as it should be, so no more errors.

I'm going to try and reproduce, and regardless, fix the error handling for this corner case.

I really appreciate you taking the time to report this issue. Also, great to see the AssetUpdater being used for other projects!

**Comment by kode80** [comment] 2016-04-21 04:05
Got to the bottom of this. As suspected it was due to the downloader not cleaning up it's delegates; so if the updater was in the process of downloading, and a local version file was deleted, and the window was refreshed (either by reopening or maximizing) - it would cause the local/remote/ui to get out of sync.

It's now fixed and in the latest official version (1.2.2), which is now available.

**Closed as completed by kode80** 2016-04-21 04:05 UTC
